// Copies the web app's design tokens (mail-vue/src/styles/tokens.css, the
// "Mist" palette) into lib/ui/tokens.g.dart, so the native app uses the
// exact same colours, radii and shadows in light and dark.
// Run from mail-app/: node tool/gen_tokens.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const css = readFileSync(join(here, '..', '..', 'mail-vue', 'src', 'styles', 'tokens.css'), 'utf8')

function block(selector) {
  const start = css.indexOf(selector + ' {')
  const end = css.indexOf('\n}', start)
  const vars = {}
  for (const m of css.slice(start, end).matchAll(/--psg-([a-z0-9-]+):\s*([^;]+);/g)) vars[m[1]] = m[2].trim()
  return vars
}

const light = block(':root')
const dark = { ...light, ...block('html.dark') }

function resolve(vars, v) {
  const m = v.match(/^var\(--psg-([a-z0-9-]+)\)$/)
  return m ? resolve(vars, vars[m[1]]) : v
}

function color(v) {
  let m = v.match(/^#([0-9a-f]{6})$/i)
  if (m) return `Color(0xFF${m[1].toUpperCase()})`
  m = v.match(/^#([0-9a-f]{3})$/i)
  if (m) return `Color(0xFF${m[1].split('').map(c => c + c).join('').toUpperCase()})`
  m = v.match(/^rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([.\d]+)\s*\)$/)
  if (m) {
    const a = Math.round(parseFloat(m[4]) * 255).toString(16).padStart(2, '0')
    const hex = [m[1], m[2], m[3]].map(n => (+n).toString(16).padStart(2, '0')).join('')
    return `Color(0x${(a + hex).toUpperCase()})`
  }
  if (v === 'transparent') return 'Color(0x00000000)'
  return null
}

const camel = s => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const colorNames = Object.keys(light).filter(k => color(resolve(light, light[k])))
const radii = Object.keys(light).filter(k => k.startsWith('radius-'))

const field = (vars, k) => `    ${camel(k)}: ${color(resolve(vars, vars[k]))},`
const out = `// GENERATED by tool/gen_tokens.mjs from mail-vue/src/styles/tokens.css — do not edit.
// ignore_for_file: lines_longer_than_80_chars
import 'package:flutter/material.dart';

/// The web app's colour tokens (--psg-*), one field per variable.
@immutable
class PsgTokens {
${colorNames.map(k => `  final Color ${camel(k)};`).join('\n')}

  const PsgTokens({
${colorNames.map(k => `    required this.${camel(k)},`).join('\n')}
  });

  static const light = PsgTokens(
${colorNames.map(k => field(light, k)).join('\n')}
  );

  static const dark = PsgTokens(
${colorNames.map(k => field(dark, k)).join('\n')}
  );
}

/// Corner radii (--psg-radius-*), in logical pixels.
abstract final class PsgRadius {
${radii.map(k => `  static const double ${camel(k.replace('radius-', ''))} = ${parseFloat(light[k])};`).join('\n')}
}
`
writeFileSync(join(here, '..', 'lib', 'ui', 'tokens.g.dart'), out)
console.log(`${colorNames.length} colours, ${radii.length} radii`)
