// Copies the web app's icon collections (mail-vue/src/icons/index.js, the
// iconify sets the UI uses: psg:, solar:, fluent-color:, …) into
// lib/ui/web_icons.g.dart as SVG strings keyed "prefix:name".
// Run from mail-app/: node tool/gen_icons.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
let src = readFileSync(join(here, '..', '..', 'mail-vue', 'src', 'icons', 'index.js'), 'utf8')
const collections = []
src = src.replace(/^import .*$/m, '').replaceAll('addCollection(', '__add(')
new Function('__add', src)(c => collections.push(c))
// Icons the web loads on demand from the Iconify API, vendored from the
// @iconify-json packages (see extra_icons.json).
collections.push(...JSON.parse(readFileSync(join(here, 'extra_icons.json'), 'utf8')))

const icons = {}
for (const c of collections) {
  for (const [name, icon] of Object.entries(c.icons)) {
    const w = icon.width ?? c.width ?? 24
    const h = icon.height ?? c.height ?? 24
    const l = icon.left ?? c.left ?? 0
    const t = icon.top ?? c.top ?? 0
    icons[`${c.prefix}:${name}`] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${l} ${t} ${w} ${h}">${icon.body}</svg>`
  }
  for (const [name, alias] of Object.entries(c.aliases ?? {})) {
    const parent = icons[`${c.prefix}:${alias.parent}`]
    if (parent) icons[`${c.prefix}:${name}`] = parent
  }
}
const esc = s => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$').replace(/\n/g, ' ') + "'"
const out = `// GENERATED by tool/gen_icons.mjs from mail-vue/src/icons — do not edit.
// ignore_for_file: lines_longer_than_80_chars

const Map<String, String> webIcons = {
${Object.entries(icons).map(([k, v]) => `  ${esc(k)}: ${esc(v)},`).join('\n')}
};
`
writeFileSync(join(here, '..', 'lib', 'ui', 'web_icons.g.dart'), out)
console.log(`${Object.keys(icons).length} icons from ${collections.length} collections: ${collections.map(c => c.prefix).join(', ')}`)
