// Copies the web app's UI strings (mail-vue/src/i18n/{zh,en}.js) into
// lib/l10n/web_strings.g.dart, so the native app uses the same wording.
// Run from mail-app/: node tool/gen_l10n.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const i18nDir = join(here, '..', '..', 'mail-vue', 'src', 'i18n')

async function load(name) {
  const src = readFileSync(join(i18nDir, `${name}.js`), 'utf8')
  const url = 'data:text/javascript;base64,' + Buffer.from(src).toString('base64')
  return (await import(url)).default
}

// vue-i18n escapes literal characters as {'x'}; unescape them here so the
// Dart side only has to handle {name} placeholders.
const unescape = s => s.replace(/\{'([^']*)'\}/g, '$1')

function dartString(s) {
  return "'" + unescape(String(s))
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\$/g, '\\$')
    .replace(/\n/g, '\\n') + "'"
}

function dartMap(obj) {
  return '{\n' + Object.entries(obj)
    .filter(([, v]) => typeof v === 'string')
    .map(([k, v]) => `  ${dartString(k)}: ${dartString(v)},`)
    .join('\n') + '\n}'
}

const zh = await load('zh')
const en = await load('en')
const out = `// GENERATED by tool/gen_l10n.mjs from mail-vue/src/i18n — do not edit.
// ignore_for_file: lines_longer_than_80_chars

const Map<String, String> webStringsZh = ${dartMap(zh)};

const Map<String, String> webStringsEn = ${dartMap(en)};
`
writeFileSync(join(here, '..', 'lib', 'l10n', 'web_strings.g.dart'), out)
console.log(`zh ${Object.keys(zh).length}, en ${Object.keys(en).length} strings`)
