// GENERATED by tool/gen_tokens.mjs from mail-vue/src/styles/tokens.css — do not edit.
// ignore_for_file: lines_longer_than_80_chars
import 'package:flutter/material.dart';

/// The web app's colour tokens (--psg-*), one field per variable.
@immutable
class PsgTokens {
  final Color canvas;
  final Color surface;
  final Color surfaceMuted;
  final Color surfaceActive;
  final Color menuActiveBg;
  final Color menuActiveText;
  final Color border;
  final Color borderStrong;
  final Color text;
  final Color textSecondary;
  final Color textMuted;
  final Color primary;
  final Color primaryHover;
  final Color primaryActive;
  final Color onPrimary;
  final Color primaryMuted;
  final Color primaryMutedStrong;
  final Color primaryLight3;
  final Color primaryLight5;
  final Color primaryLight7;
  final Color primaryLight8;
  final Color primaryLight9;
  final Color primaryDark2;
  final Color success;
  final Color successLight3;
  final Color successLight5;
  final Color successLight7;
  final Color successLight8;
  final Color successLight9;
  final Color successDark2;
  final Color warning;
  final Color warningLight3;
  final Color warningLight5;
  final Color warningLight7;
  final Color warningLight8;
  final Color warningLight9;
  final Color warningDark2;
  final Color info;
  final Color infoLight3;
  final Color infoLight5;
  final Color infoLight7;
  final Color infoLight8;
  final Color infoLight9;
  final Color infoDark2;
  final Color danger;
  final Color dangerLight3;
  final Color dangerLight5;
  final Color dangerLight7;
  final Color dangerLight8;
  final Color dangerLight9;
  final Color dangerDark2;
  final Color dangerHover;
  final Color dangerActive;
  final Color dangerMuted;
  final Color focus;
  final Color htmlShadowBg;

  const PsgTokens({
    required this.canvas,
    required this.surface,
    required this.surfaceMuted,
    required this.surfaceActive,
    required this.menuActiveBg,
    required this.menuActiveText,
    required this.border,
    required this.borderStrong,
    required this.text,
    required this.textSecondary,
    required this.textMuted,
    required this.primary,
    required this.primaryHover,
    required this.primaryActive,
    required this.onPrimary,
    required this.primaryMuted,
    required this.primaryMutedStrong,
    required this.primaryLight3,
    required this.primaryLight5,
    required this.primaryLight7,
    required this.primaryLight8,
    required this.primaryLight9,
    required this.primaryDark2,
    required this.success,
    required this.successLight3,
    required this.successLight5,
    required this.successLight7,
    required this.successLight8,
    required this.successLight9,
    required this.successDark2,
    required this.warning,
    required this.warningLight3,
    required this.warningLight5,
    required this.warningLight7,
    required this.warningLight8,
    required this.warningLight9,
    required this.warningDark2,
    required this.info,
    required this.infoLight3,
    required this.infoLight5,
    required this.infoLight7,
    required this.infoLight8,
    required this.infoLight9,
    required this.infoDark2,
    required this.danger,
    required this.dangerLight3,
    required this.dangerLight5,
    required this.dangerLight7,
    required this.dangerLight8,
    required this.dangerLight9,
    required this.dangerDark2,
    required this.dangerHover,
    required this.dangerActive,
    required this.dangerMuted,
    required this.focus,
    required this.htmlShadowBg,
  });

  static const light = PsgTokens(
    canvas: Color(0xFFE8EBEF),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFF2F2F7),
    surfaceActive: Color(0xFFE5E5EA),
    menuActiveBg: Color(0xFFFFFFFF),
    menuActiveText: Color(0xFF1C1C1E),
    border: Color(0xFFE5E5EA),
    borderStrong: Color(0xFF1C1C1E),
    text: Color(0xFF1C1C1E),
    textSecondary: Color(0xFF3C3C43),
    textMuted: Color(0xFF636366),
    primary: Color(0xFFC2410C),
    primaryHover: Color(0xFFA8380A),
    primaryActive: Color(0xFF9A3412),
    onPrimary: Color(0xFFFFFFFF),
    primaryMuted: Color(0x17C2410C),
    primaryMutedStrong: Color(0x29C2410C),
    primaryLight3: Color(0xFFD4703F),
    primaryLight5: Color(0xFFE0A07F),
    primaryLight7: Color(0xFFEFC7B2),
    primaryLight8: Color(0xFFF5DCCF),
    primaryLight9: Color(0xFFFDEEE7),
    primaryDark2: Color(0xFF9A3412),
    success: Color(0xFF25613A),
    successLight3: Color(0xFF4F8662),
    successLight5: Color(0xFF86AE93),
    successLight7: Color(0xFFBCD5C4),
    successLight8: Color(0xFFD3E5D8),
    successLight9: Color(0xFFE2F0E6),
    successDark2: Color(0xFF1D4D2E),
    warning: Color(0xFF9A6200),
    warningLight3: Color(0xFFB5873A),
    warningLight5: Color(0xFFCFAE73),
    warningLight7: Color(0xFFE6D3AE),
    warningLight8: Color(0xFFF0E3C9),
    warningLight9: Color(0xFFFAF1DE),
    warningDark2: Color(0xFF7A4E00),
    info: Color(0xFF636366),
    infoLight3: Color(0xFF86868B),
    infoLight5: Color(0xFFAEAEB2),
    infoLight7: Color(0xFFD1D1D6),
    infoLight8: Color(0xFFE5E5EA),
    infoLight9: Color(0xFFF2F2F7),
    infoDark2: Color(0xFF48484A),
    danger: Color(0xFFC62828),
    dangerLight3: Color(0xFFD45A5A),
    dangerLight5: Color(0xFFE39393),
    dangerLight7: Color(0xFFF0C2C2),
    dangerLight8: Color(0xFFF5D6D6),
    dangerLight9: Color(0xFFFBEAEA),
    dangerDark2: Color(0xFFA12020),
    dangerHover: Color(0xFFA12020),
    dangerActive: Color(0xFF861A1A),
    dangerMuted: Color(0x17C62828),
    focus: Color(0xFFC2410C),
    htmlShadowBg: Color(0x00000000),
  );

  static const dark = PsgTokens(
    canvas: Color(0xFF0E0E10),
    surface: Color(0xFF1C1C1F),
    surfaceMuted: Color(0xFF2A2A2E),
    surfaceActive: Color(0xFF3A3A3F),
    menuActiveBg: Color(0xFF1C1C1F),
    menuActiveText: Color(0xFFF2F2F7),
    border: Color(0xFF2E2E33),
    borderStrong: Color(0xFFF2F2F7),
    text: Color(0xFFF2F2F7),
    textSecondary: Color(0xFFD1D1D6),
    textMuted: Color(0xFF9A9AA0),
    primary: Color(0xFFFF8A50),
    primaryHover: Color(0xFFFF9E6B),
    primaryActive: Color(0xFFF2783A),
    onPrimary: Color(0xFF1C1C1E),
    primaryMuted: Color(0x24FF8A50),
    primaryMutedStrong: Color(0x38FF8A50),
    primaryLight3: Color(0xFFC96B3E),
    primaryLight5: Color(0xFF8E4E30),
    primaryLight7: Color(0xFF5C3524),
    primaryLight8: Color(0xFF45291D),
    primaryLight9: Color(0xFF2F1E17),
    primaryDark2: Color(0xFFFFB38C),
    success: Color(0xFF6BCB91),
    successLight3: Color(0xFF519A70),
    successLight5: Color(0xFF3F7254),
    successLight7: Color(0xFF31523F),
    successLight8: Color(0xFF294236),
    successLight9: Color(0xFF203229),
    successDark2: Color(0xFF88D9A7),
    warning: Color(0xFFE8B64F),
    warningLight3: Color(0xFFB68F48),
    warningLight5: Color(0xFF846B3B),
    warningLight7: Color(0xFF5C4B2E),
    warningLight8: Color(0xFF463B27),
    warningLight9: Color(0xFF342D20),
    warningDark2: Color(0xFFF0C978),
    info: Color(0xFF9A9AA0),
    infoLight3: Color(0xFF7C7C82),
    infoLight5: Color(0xFF5E5E63),
    infoLight7: Color(0xFF444448),
    infoLight8: Color(0xFF36363A),
    infoLight9: Color(0xFF2A2A2E),
    infoDark2: Color(0xFFC1C1C6),
    danger: Color(0xFFFF6B6B),
    dangerLight3: Color(0xFFD45656),
    dangerLight5: Color(0xFFA04444),
    dangerLight7: Color(0xFF6F3232),
    dangerLight8: Color(0xFF522828),
    dangerLight9: Color(0xFF3A2020),
    dangerDark2: Color(0xFFFF8A8A),
    dangerHover: Color(0xFFFF8484),
    dangerActive: Color(0xFFE05555),
    dangerMuted: Color(0x29FF6B6B),
    focus: Color(0xFFFF8A50),
    htmlShadowBg: Color(0xFF1C1C1F),
  );
}

/// Corner radii (--psg-radius-*), in logical pixels.
abstract final class PsgRadius {
  static const double xs = 8;
  static const double sm = 10;
  static const double md = 14;
  static const double lg = 20;
  static const double xl = 24;
  static const double full = 999;
}
